### ISSUE TITLE
References to IMO MSC.232(82) should be updated

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/98-interoperability#16] opened 2023-09-11 18:38 UTC
References to IMO MSC.232(82) should be updated to reference MSC.530(106)

![image](https://github.com/iho-ohi/98-interoperability/assets/62906211/d00f784a-25c9-48a8-8f4f-00e0530489a5)

**Comment by rmalyankar** [comment] 2023-09-19 03:55
Duplicate of #12

**Comment by rmalyankar** [comment] 2023-09-19 04:06
Reclassifying this as applying to "main" interoperability - changes to Annex C duplicate #12.

- [ ] MSC 232(82)
- [ ] SENC

**Comment by kusala9** [comment] 2024-06-13 12:33
done in version 1.2.0

**Closed by kusala9** 2024-06-13 12:33 UTC
Labels: duplicate, ICMain
